GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
        "name": "Os irmãos Karamazov",
        "description": "Literatura russa",
        "image_url": "https://via.placeholder.com/150",
        "price": 115
}


###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiU3Rld2llIiwiaWF0IjoxNzA2OTA5NTg3LCJleHAiOjE3MDY5MDk2NDd9.ZKrKpd2Mz9O6bNUbAdhPvUzbLlTN89leKPIk54aw6lU

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiU3Rld2llIiwiaWF0IjoxNzA2OTEwNDc2LCJleHAiOjE3MDY5MTA1MzZ9.ipHgWUZuCiFW7ffM-YsW2cAJRLESD1APSPtpor0xwkI
{
    "items": [
        {
            "product_id": "09a10028-471a-49e5-98e7-8de7a9e279aa",
            "quantity": 1
        },
        {
            "product_id": "f15a402f-874c-414e-a467-79f06e3e57d1",
            "quantity": 5
        }
    ],
    "card_hash": "1a2s3d4f"

}

###
POST http://localhost:3000/auth/login
Content-Type: application/json
{
    "username": "abcd",
    "password": "password"
}
